# docker compose -f docker/infra-docker.yml --env-file ./docker/mongodb.env up
# docker compose -f docker/infra-docker.yml --env-file ./docker/mongodb.env down --volumes --remove-orphans
# docker stats --no-stream

# docker system prune -a -f && docker volume prune -f && docker network prune -f && docker container prune -f

# URLs de Acesso:
# MongoDB: localhost:27018
# Jaeger UI: http://localhost:16686
# OpenTelemetry Collector gRPC: localhost:4317
# OpenTelemetry Collector HTTP: localhost:4318

# https://devblogs.microsoft.com/dotnet/mongodb-ef-core-provider-whats-new/
# https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-9.0&tabs=visual-studio
# https://www.jaegertracing.io/docs/latest/getting-started/
# https://hub.docker.com/r/mongodb/mongodb-atlas-local

services:
  mongodb-service:
    image: mongodb/mongodb-community-server:7.0.21-ubi8
    container_name: mongodb-container
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${ADMIN_MONGODB_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${ADMIN_MONGODB_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - canal-deploy-network

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.130.1
    container_name: opentelemetry-collector-container
    restart: always
    ports:
      - 4317:4317 # Porta gRPC
      - 4318:4318 # Porta HTTP
    volumes:
      - ./collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    depends_on:
      - jaeger-service
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - canal-deploy-network

  jaeger-service:
    image: jaegertracing/all-in-one:1.71.0
    container_name: jaeger-container
    restart: always
    ports:
      - 16686:16686
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_OTLP_ENABLED: true
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
      COLLECTOR_OTLP_GRPC_HOST_PORT: :4317
      COLLECTOR_OTLP_HTTP_HOST_PORT: :4318
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - canal-deploy-network

networks:
  canal-deploy-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
