@LocalHost = http://localhost:7007

POST {{LocalHost}}/boat/
Content-Type: application/json
{
    "Name": "ALARRIBA II",
    "Size": 6,
    "License": true
}

###

GET {{LocalHost}}/boat/all

###

GET {{LocalHost}}/boatbyid/ea519a38-58c4-40a2-ad17-8a7177378964

###

DELETE {{LocalHost}}/boat/ea519a38-58c4-40a2-ad17-8a7177378964

###

PUT {{LocalHost}}/boat/ea519a38-58c4-40a2-ad17-8a7177378964
Content-Type: application/json
{
    "Name": "Meu Iate",
    "Size": 12,
    "License": true
}