@LocalHost = http://localhost:7007

POST {{LocalHost}}/api/v1/boats
Content-Type: application/json
{
    "Name": "ALARRIBA II",
    "Size": 6,
    "License": true
}

###

GET {{LocalHost}}/all

###

GET {{LocalHost}}/searchbyid/ea519a38-58c4-40a2-ad17-8a7177378964

###

DELETE {{LocalHost}}/ea519a38-58c4-40a2-ad17-8a7177378964

###

PUT {{LocalHost}}/ea519a38-58c4-40a2-ad17-8a7177378964
Content-Type: application/json
{
    "Name": "Meu Iate",
    "Size": 12,
    "License": true
}