# @HostAddress = http://localhost:7007

POST {{HostAddress}}/api/v1/boats
Content-Type: application/json
{
    "Name": "ALARRIBA II",
    "Size": 6,
    "License": true
}

###

GET {{HostAddress}}/api/v1/boats/all

###

GET {{HostAddress}}/api/v1/boats/searchbyid/67b869ff71653506ba2fc4fd

###
GET {{HostAddress}}/api/v1/boats/ALARRIBA%20II

###

DELETE {{LocalHost}}/api/v1/boats/67b869dd71653506ba2fc4fc

###

PUT {{HostAddress}}/api/v1/boats/ea519a38-58c4-40a2-ad17-8a7177378964
Content-Type: application/json
{
    "Name": "Meu Iate",
    "Size": 12,
    "License": true
}