@DEPPLOY.MongoBDEFCore.API_HostAddress = http://localhost:7007

POST {{DEPPLOY.MongoBDEFCore.API_HostAddress}}/test/
Content-Type: application/json
  {
      "Name": "Test",
      "Size": 10,
      "License": true
  }

###
