# @HostAddress = http://localhost:7007

POST {{HostAddress}}/api/v1/marinas
Content-Type: application/json
{
    "Name": "Marina Original"
}

###

GET {{HostAddress}}/api/v1/marinas/all

###

GET {{HostAddress}}/api/v1/marinas/searchbyid/67b9cbe6e3555d8da33626c3

###
GET {{HostAddress}}/api/v1/marinas/Marina%20Original

###

DELETE {{HostAddress}}/api/v1/marinas/67b9cbe6e3555d8da33626c3

###

PUT {{HostAddress}}/api/v1/marinas/a95f06ca-55f6-44ef-a9bc-8880931ef942
Content-Type: application/json
{
    "Name": "Marina Novo Barco"
}