name: Example Usage

on:
  workflow_dispatch:

jobs:
  get-project-version:
    uses: felipementel/project-full-version/.github/workflows/get-version.yml@main
    with:
      csproj: "./src/DEPLOY.MongoDBEFCore.API/DEPLOY.MongoDBEFCore.API.csproj"
    outputs:
      version: ${{ steps.get-version.outputs.tag }}

  build-and-deploy:
    needs: get-project-version
    runs-on: ubuntu-latest
    steps:
      - name: Exibir versão extraída
        run: echo "Versão extraída: ${{ needs.get-project-version.outputs.version }}"
        
      - name: Criar Tag no GitHub
        run: |
          git tag v${{ needs.get-project-version.outputs.version }}
          git push origin v${{ needs.get-project-version.outputs.version }}
